name: Build & Test

on:
  pull_request:
    branches:
      - '*'

#env:
#  DOTNET_VERSION: '9.0.x'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Setup .NET
      #  uses: actions/setup-dotnet@v4
      #  with:
      #    dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Print .NET version
        run: |
          dotnet --version
          dotnet --list-sdks

      - name: Build
        run: |
          dotnet restore dotnet-packaging.sln
          dotnet pack dotnet-packaging.sln -c Release -o pkg/
          cp demo/Directory.Build.props pkg/
          cp demo/version.txt pkg/

      - name: Test
        run: dotnet test Packaging.Targets.Tests/Packaging.Targets.Tests.csproj -l "trx;LogFileName=pkg/Packaging.Targets.Tests.trx"
